/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import Modelo.Controle;
import Modelo.Estaticos;
import Modelo.Carro;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class frmPesquisarEditarExcluir extends javax.swing.JDialog
{

    /**
     * Creates new form frmPesquisarEditarExcluir
     */
    public frmPesquisarEditarExcluir(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        txvAno = new javax.swing.JTextField();
        txvCor = new javax.swing.JTextField();
        txvModelo = new javax.swing.JTextField();
        txvFabricante = new javax.swing.JTextField();
        txvID = new javax.swing.JTextField();
        btnPesquisarID = new javax.swing.JButton();
        btnPesquisarFabricante = new javax.swing.JButton();
        btnPesquisarModelo = new javax.swing.JButton();
        txvValor = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        lblCor = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblFabricante = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar, Editar e Excluir");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnExcluir.setBackground(new java.awt.Color(77, 80, 82));
        btnExcluir.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(204, 204, 204));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txvAno.setBackground(new java.awt.Color(245, 245, 245));
        txvAno.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txvAno.setForeground(new java.awt.Color(0, 0, 0));

        txvCor.setBackground(new java.awt.Color(245, 245, 245));
        txvCor.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txvCor.setForeground(new java.awt.Color(0, 0, 0));

        txvModelo.setBackground(new java.awt.Color(245, 245, 245));
        txvModelo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txvModelo.setForeground(new java.awt.Color(0, 0, 0));

        txvFabricante.setBackground(new java.awt.Color(245, 245, 245));
        txvFabricante.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txvFabricante.setForeground(new java.awt.Color(0, 0, 0));

        txvID.setBackground(new java.awt.Color(245, 245, 245));
        txvID.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txvID.setForeground(new java.awt.Color(0, 0, 0));

        btnPesquisarID.setBackground(new java.awt.Color(77, 80, 82));
        btnPesquisarID.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnPesquisarID.setForeground(new java.awt.Color(204, 204, 204));
        btnPesquisarID.setText("Pesquisar ID");
        btnPesquisarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarIDActionPerformed(evt);
            }
        });

        btnPesquisarFabricante.setBackground(new java.awt.Color(77, 80, 82));
        btnPesquisarFabricante.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnPesquisarFabricante.setForeground(new java.awt.Color(204, 204, 204));
        btnPesquisarFabricante.setText("Pesquisar Fabricante");
        btnPesquisarFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarFabricanteActionPerformed(evt);
            }
        });

        btnPesquisarModelo.setBackground(new java.awt.Color(77, 80, 82));
        btnPesquisarModelo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnPesquisarModelo.setForeground(new java.awt.Color(204, 204, 204));
        btnPesquisarModelo.setText("Pesquisar Modelo");
        btnPesquisarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarModeloActionPerformed(evt);
            }
        });

        txvValor.setBackground(new java.awt.Color(245, 245, 245));
        txvValor.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txvValor.setForeground(new java.awt.Color(0, 0, 0));
        txvValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txvValorActionPerformed(evt);
            }
        });

        lblValor.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblValor.setForeground(new java.awt.Color(0, 0, 0));
        lblValor.setText("Valor");

        lblCor.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblCor.setForeground(new java.awt.Color(0, 0, 0));
        lblCor.setText("Cor");

        lblAno.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblAno.setForeground(new java.awt.Color(0, 0, 0));
        lblAno.setText("Ano");

        lblModelo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(0, 0, 0));
        lblModelo.setText("Modelo");

        lblFabricante.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblFabricante.setForeground(new java.awt.Color(0, 0, 0));
        lblFabricante.setText("Fabricante");

        lblID.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblID.setForeground(new java.awt.Color(0, 0, 0));
        lblID.setText("ID");

        btnEditar.setBackground(new java.awt.Color(77, 80, 82));
        btnEditar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(204, 204, 204));
        btnEditar.setText("Editar");
        btnEditar.setBorderPainted(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txvFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFabricante)
                            .addComponent(lblModelo)
                            .addComponent(txvModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblID)
                            .addComponent(txvID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPesquisarID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPesquisarFabricante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPesquisarModelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAno)
                            .addComponent(txvAno, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCor)
                            .addComponent(txvCor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txvValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValor))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txvID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFabricante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txvFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblModelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txvModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAno)
                        .addGap(8, 8, 8)
                        .addComponent(txvAno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCor)
                        .addGap(9, 9, 9)
                        .addComponent(txvCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblValor)
                        .addGap(9, 9, 9)
                        .addComponent(txvValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ShowMessageAndClearTxv(Component component, Object message)
    {
        JOptionPane.showMessageDialog(component, message);
        txvID.setText("");
        txvFabricante.setText("");
        txvModelo.setText("");
        txvCor.setText("");
        txvAno.setText("");
        txvValor.setText("");
    }
    private void btnPesquisarFabricanteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPesquisarFabricanteActionPerformed
    {//GEN-HEADEREND:event_btnPesquisarFabricanteActionPerformed
        Controle controle = new Controle();
        List<Carro> listaCarros = controle.PesquisarCarroFabricante(txvFabricante.getText());
        if (listaCarros.size() == 0 || !controle.getMensagem().equals(""))
        {
            ShowMessageAndClearTxv(null, "Não existe registros com esta pesquisa");
        }
        if (listaCarros.size() == 1)
        {
            txvID.setText(String.valueOf(listaCarros.get(0).getID()));
            txvFabricante.setText(listaCarros.get(0).getFabricante());
            txvModelo.setText(listaCarros.get(0).getModelo());
            txvCor.setText(listaCarros.get(0).getCor());
            txvAno.setText(String.valueOf(listaCarros.get(0).getAnoFabricao()));
            txvValor.setText(String.valueOf(listaCarros.get(0).getValor()));
        }
        if (listaCarros.size() > 1)
        {
            Estaticos.listaCarro = listaCarros;
            frmSelecao frmS = new frmSelecao(null, true);
            frmS.setVisible(true);
            txvID.setText(String.valueOf(Estaticos.carro.getID()));
            txvFabricante.setText(String.valueOf(Estaticos.carro.getFabricante()));
            txvModelo.setText(String.valueOf(Estaticos.carro.getModelo()));
            txvCor.setText(String.valueOf(Estaticos.carro.getCor()));
            txvAno.setText(String.valueOf(Estaticos.carro.getAnoFabricao()));
            txvValor.setText(String.valueOf(Estaticos.carro.getValor()));
        }
    }//GEN-LAST:event_btnPesquisarFabricanteActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEditarActionPerformed
    {//GEN-HEADEREND:event_btnEditarActionPerformed

        Controle controle = new Controle();
        Carro PesquisaId = controle.PesquisarCarroID(txvID.getText());

        if (PesquisaId.equals("") || !controle.getMensagem().equals(""))
        {
            ShowMessageAndClearTxv(null, "Não existe registros com esta pesquisa");
        }
        else
        {
            List<String> dadosCarro = new ArrayList<>();
            dadosCarro.add(txvID.getText());
            dadosCarro.add(txvFabricante.getText());
            dadosCarro.add(txvModelo.getText());
            dadosCarro.add(txvCor.getText());
            dadosCarro.add(txvAno.getText());
            dadosCarro.add(txvValor.getText());
            controle.EditarCarros(dadosCarro);
            JOptionPane.showMessageDialog(null, controle.getMensagem());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExcluirActionPerformed
    {//GEN-HEADEREND:event_btnExcluirActionPerformed
        Controle controle = new Controle();
        Carro PesquisaId = controle.PesquisarCarroID(txvID.getText());

        if (PesquisaId.equals("") || !controle.getMensagem().equals(""))
        {
            ShowMessageAndClearTxv(null, "Nenhum registros com esta pesquisa");
        }
        else
        {
            int resp = JOptionPane.showConfirmDialog(null, "Deseja excluir este veículo?",
                    "Exclusão", JOptionPane.YES_NO_OPTION);
            if (resp == JOptionPane.YES_OPTION)
            {
                controle.ExcluirCarro(txvID.getText());
                JOptionPane.showMessageDialog(null, controle.getMensagem());
                txvID.setText("");
                txvFabricante.setText("");
                txvModelo.setText("");
                txvCor.setText("");
                txvAno.setText("");
                txvValor.setText("");
            }
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarModeloActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPesquisarModeloActionPerformed
    {//GEN-HEADEREND:event_btnPesquisarModeloActionPerformed
        Controle controle = new Controle();
        List<Carro> listaCarros = controle.PesquisarCarroModelo(txvModelo.getText());
        if (listaCarros.size() == 0 || !controle.getMensagem().equals(""))
        {
            ShowMessageAndClearTxv(null, "Não existe registros com esta pesquisa");
        }
        if (listaCarros.size() == 1)
        {
            txvID.setText(String.valueOf(listaCarros.get(0).getID()));
            txvFabricante.setText(listaCarros.get(0).getFabricante());
            txvModelo.setText(listaCarros.get(0).getModelo());
            txvCor.setText(listaCarros.get(0).getCor());
            txvAno.setText(String.valueOf(listaCarros.get(0).getAnoFabricao()));
            txvValor.setText(String.valueOf(listaCarros.get(0).getValor()));
        }
        if (listaCarros.size() > 1)
        {
            Estaticos.listaCarro = listaCarros;
            frmSelecao frmS = new frmSelecao(null, true);
            frmS.setVisible(true);
            txvID.setText(String.valueOf(Estaticos.carro.getID()));
            txvFabricante.setText(String.valueOf(Estaticos.carro.getFabricante()));
            txvModelo.setText(String.valueOf(Estaticos.carro.getModelo()));
            txvCor.setText(String.valueOf(Estaticos.carro.getCor()));
            txvAno.setText(String.valueOf(Estaticos.carro.getAnoFabricao()));
            txvValor.setText(String.valueOf(Estaticos.carro.getValor()));
        }
    }//GEN-LAST:event_btnPesquisarModeloActionPerformed

    private void btnPesquisarIDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPesquisarIDActionPerformed
    {//GEN-HEADEREND:event_btnPesquisarIDActionPerformed
        Controle controle = new Controle();
        Carro carro = controle.PesquisarCarroID(txvID.getText());
        if (controle.getMensagem().equals(""))
        {
            txvFabricante.setText(carro.getFabricante());
            txvModelo.setText(carro.getModelo());
            txvCor.setText(carro.getCor());
            txvAno.setText(String.valueOf(carro.getAnoFabricao()));
            txvValor.setText(String.valueOf(carro.getValor()));
        }
        else
        {
            ShowMessageAndClearTxv(null, "Não existe registros com esta pesquisa");
        }
    }//GEN-LAST:event_btnPesquisarIDActionPerformed

    private void txvValorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txvValorActionPerformed
    {//GEN-HEADEREND:event_txvValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txvValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPesquisarEditarExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPesquisarEditarExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPesquisarEditarExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPesquisarEditarExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmPesquisarEditarExcluir dialog = new frmPesquisarEditarExcluir(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisarFabricante;
    private javax.swing.JButton btnPesquisarID;
    private javax.swing.JButton btnPesquisarModelo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblFabricante;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txvAno;
    private javax.swing.JTextField txvCor;
    private javax.swing.JTextField txvFabricante;
    private javax.swing.JTextField txvID;
    private javax.swing.JTextField txvModelo;
    private javax.swing.JTextField txvValor;
    // End of variables declaration//GEN-END:variables

    private String toString(int anoFabricacao)
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
